# servers
FILE_SERVER = 8000
DIR_SERVER = 8001
LOCK_SERVER = 8002
REP_SERVER = 8003

# variables
LOCK_ATTEMPTS = 1

# server messages
CLIENT_WRITE_FILE = 'WRITE_FILE: {}\nDIRECTORY: {}\nCLIENT: {}\nDATA: {}\n\n'
CLIENT_READ_FILE = 'READ_FILE: {}\nDIRECTORY: {}\nCLIENT: {}\n\n'
REQUEST_FILE_ID = 'REQUEST_FILE_ID: {}\nDIRECTORY: {}\nFUNCTION: {}\n\n'
RETURN_FILE_ID = 'RETURN_FILE_ID: {}\nSERVER_IP: {}\nSERVER_PORT: {}\n\n'

CLIENT_REQUEST_LOCK = 'REQUEST_LOCK: {}\nDIRECTORY: {}\nCLIENT: {}\n\n'
CLIENT_REQUEST_UNLOCK = 'REQUEST_UNLOCK: {}\NDIRECTORY: {}\nCLIENT: {}\n\n'
REQUEST_LOCK = 'REQUEST_LOCK: {}\nCLIENT: {}\n\n'
REQUEST_USAGE = 'REQUEST_USAGE: {}\nCLIENT: {}\n\n'
REQUEST_UNLOCK = 'REQUEST_UNLOCK: {}\nCLIENT: {}\n\n'
LOCK_STATUS = 'LOCK_STATUS: {}\n\n'

FILE_NOT_FOUND = 'FILE_NOT_FOUND: {}\n DIRECTORY: {}\n\n'
REQUEST_FILE_DATA = 'REQUEST_FILE_DATA: {}\n\n'
UPDATE_FILE_DATA = 'UPDATE_FILE_DATA: {}\nDATA: {}\n\n'
DELETE_FILE_DATA = 'DELETE_FILE_DATA: {}\n\n'
RETURN_FILE_DATA = 'RETURN_FILE_DATA: {}\n\n'

SUCCESS = 'SUCCESS: {}\n\n'
FAILURE = 'FAILURE: {}\nREASON: {}\n\n'
RETURN_FILE = 'FILE_NAME: {}\nDIRECTORY: {}\nDATA: {}\n\n'
ERROR_MSG = 'ERROR: {}\n\n'